name: Daily 4 Storytelling Videos

on:
  schedule:
    - cron: "30 3 * * *"   # सुबह 9:00 AM IST
    - cron: "30 7 * * *"   # दोपहर 1:00 PM IST
    - cron: "30 11 * * *"  # शाम 5:00 PM IST
    - cron: "30 15 * * *"  # रात 9:00 PM IST
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Storytelling Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: python storyteller_youtube_agent.py
