import os
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

# Credentials from GitHub Secrets
creds = Credentials.from_authorized_user_info({
    "client_id": os.environ["YT_CLIENT_SECRET"],
    "refresh_token": os.environ["YT_REFRESH_TOKEN"],
    "token_uri": "https://oauth2.googleapis.com/token"
})

youtube = build("youtube", "v3", credentials=creds)

request = youtube.videos().insert(
    part="snippet,status",
    body={
        "snippet": {
            "title": "Daily Storytelling Video 🎬",
            "description": "Automated storytelling video generated by AI.",
            "tags": ["AI", "Storytelling", "Automation"]
        },
        "status": {
            "privacyStatus": "public"
        }
    },
    media_body=MediaFileUpload("output.mp4")
)

response = request.execute()
print("✅ Video Uploaded:", response.get("id"))
